export const ENEMIES = {
  chaser: {
    id: "chaser",
    name: "Chaser",
    color: "#ff7b7b",
    maxHp: 38,
    moveSpeed: 2.75,
    damage: 12,
    rewardGold: 10,
    ai: "chaser",
    radius: 0.34,
  },
  spitter: {
    id: "spitter",
    name: "Spitter",
    color: "#c98cff",
    maxHp: 28,
    moveSpeed: 1.7,
    damage: 10,
    rewardGold: 11,
    ai: "spitter",
    radius: 0.31,
    projectileSpeed: 6.4,
    fireInterval: 1.3,
  },
  charger: {
    id: "charger",
    name: "Charger",
    color: "#ffb36a",
    maxHp: 48,
    moveSpeed: 2.35,
    damage: 18,
    rewardGold: 14,
    ai: "charger",
    radius: 0.36,
    dashSpeed: 6.1,
    windup: 0.48,
  },
  boss: {
    id: "boss",
    name: "Titan Core",
    color: "#65b7ff",
    maxHp: 280,
    moveSpeed: 1.35,
    damage: 16,
    rewardGold: 70,
    ai: "boss",
    radius: 0.7,
    projectileSpeed: 7.4,
    fireInterval: 1.1,
  },
};
