export const ENEMIES = {
  chaser: {
    id: "chaser",
    name: "Chaser",
    color: "#ff7b7b",
    maxHp: 38,
    moveSpeed: 1.9,
    damage: 12,
    rewardGold: 10,
    ai: "chaser",
    radius: 0.34,
  },
  spitter: {
    id: "spitter",
    name: "Spitter",
    color: "#c98cff",
    maxHp: 28,
    moveSpeed: 1.5,
    damage: 10,
    rewardGold: 11,
    ai: "spitter",
    radius: 0.31,
    projectileSpeed: 6.4,
    fireInterval: 1.3,
  },
  charger: {
    id: "charger",
    name: "Charger",
    color: "#ffb36a",
    maxHp: 48,
    moveSpeed: 1.35,
    damage: 18,
    rewardGold: 14,
    ai: "charger",
    radius: 0.36,
    dashSpeed: 4.2,
    windup: 0.6,
  },
  boss: {
    id: "boss",
    name: "Titan Core",
    color: "#65b7ff",
    maxHp: 280,
    moveSpeed: 1.15,
    damage: 16,
    rewardGold: 70,
    ai: "boss",
    radius: 0.7,
    projectileSpeed: 7.4,
    fireInterval: 1.1,
  },
};
