export const SKILL_TREE = [
  {
    id: "ballistics",
    branch: "Weapons",
    name: "Ballistics",
    description: "Increase all weapon damage by 8% per level.",
    maxLevel: 3,
    costs: [2, 4, 7],
    prerequisites: [],
    effect: { damageMultiplier: 0.08 },
  },
  {
    id: "rapidCycling",
    branch: "Weapons",
    name: "Rapid Cycling",
    description: "Increase fire rate by 6% per level.",
    maxLevel: 2,
    costs: [3, 6],
    prerequisites: ["ballistics"],
    effect: { fireRateMultiplier: 0.06 },
  },
  {
    id: "runner",
    branch: "Mobility",
    name: "Runner",
    description: "Gain a flat 0.18 movement speed per level.",
    maxLevel: 3,
    costs: [2, 4, 6],
    prerequisites: [],
    effect: { flatSpeed: 0.18 },
  },
  {
    id: "scavenger",
    branch: "Mobility",
    name: "Scavenger",
    description: "Gain 10% more Gold per level.",
    maxLevel: 2,
    costs: [3, 5],
    prerequisites: ["runner"],
    effect: { goldMultiplier: 0.1 },
  },
  {
    id: "droneCore",
    branch: "Summons",
    name: "Drone Core",
    description: "Unlock a companion drone that scales with rooms at a lower rate than the player.",
    maxLevel: 1,
    costs: [4],
    prerequisites: [],
    effect: { unlockCompanion: true },
  },
  {
    id: "dronePlating",
    branch: "Summons",
    name: "Drone Plating",
    description: "Increase companion durability and damage by 10% per level.",
    maxLevel: 2,
    costs: [4, 7],
    prerequisites: ["droneCore"],
    effect: { companionPower: 0.1 },
  },
  {
    id: "droneUplink",
    branch: "Summons",
    name: "Drone Uplink",
    description: "Increase companion fire rate and turn speed by 9% per level.",
    maxLevel: 2,
    costs: [4, 7],
    prerequisites: ["droneCore"],
    effect: { companionUplink: 0.09 },
  },
];
