export const WEAPONS = {
  pistol: {
    id: "pistol",
    name: "Pistol",
    description: "Steady and precise. Strong baseline for room one.",
    damage: 14,
    fireInterval: 0.28,
    projectileSpeed: 10,
    spread: 0.02,
    pellets: 1,
    projectileRadius: 0.13,
    color: "#8ec5ff",
    cost: 0,
    rarity: "starter",
  },
  shotgun: {
    id: "shotgun",
    name: "Shotgun",
    description: "Wide pellet burst. Excels at close room control.",
    damage: 7,
    fireInterval: 0.72,
    projectileSpeed: 8.8,
    spread: 0.26,
    pellets: 5,
    projectileRadius: 0.12,
    color: "#ffd166",
    cost: 72,
    rarity: "shop",
  },
  smg: {
    id: "smg",
    name: "SMG",
    description: "High rate of fire with small spread and lighter hits.",
    damage: 8,
    fireInterval: 0.12,
    projectileSpeed: 11.2,
    spread: 0.08,
    pellets: 1,
    projectileRadius: 0.11,
    color: "#78f0b4",
    cost: 76,
    rarity: "shop",
  },
};

export const SHOP_WEAPON_IDS = ["shotgun", "smg"];
